checks:
    php:
        code_rating: true
        duplication: true
build:
    tests:
        override:
        -
            command: 'phpunit --coverage-clover=build/clover.xml'
                coverage:
                    file: 'build/clover.xml'
                    format: 'clover'
